### ISSUE TITLE
[porter/aks] portal says template not available

### ISSUE THREAD

**Issue by squillace** [Azure/azure-cnab-quickstarts#30]
## Expected Behavior
Template launches

## Actual Behavior
![image](https://user-images.githubusercontent.com/1422718/70808944-d12a6700-1d8e-11ea-8d52-249b70dc5e1c.png)

Turns out you have extra chars in the image launching url: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-cnab-quickstarts%2Faks-28%2Fporter%2Faks%2Fazuredeploy-simple.json

the "aks-28" in the middle needs to be replaced with "master" I believe. I'd do a quick review of other templates if you make this change globally.

## Steps to Reproduce the Problem

  1. Click on the Simple Deploy button.
![image](https://user-images.githubusercontent.com/1422718/70808908-b3f59880-1d8e-11ea-9636-6697673c9478.png)

  1. Bug o rama.
  1.

**Comment by squillace** [comment]
@MikeLarah upside is that when the url is corrected, the template deploys properly! Step one!

**Comment by MikeLarah** [comment]
This URL should be rewritten by the CI workflow that runs after merging a PR to master. However it looks like this workflow failed in this instance https://github.com/Azure/azure-cnab-quickstarts/commit/87fa672527abb1a3db09480747e891de7268f6a5/checks?check_suite_id=356956819

It looks like there is possibly a race condition in the step that commits the changes back to the branch. I'll investigate.

**Comment by MikeLarah** [comment]
@squillace the other quickstarts should not currently be affected by this

**Comment by squillace** [comment]
if the run fails, the commit should remain the same and we should not update the readme with anything. We should remain in the previous state, yes? 

```
It looks like the branch being examined is a detached Head pointing to commit '87fa672'. Without a proper branch name GitVersion cannot determine the build version.::error::Unexpected token I in JSON at position 0
##[error]Node run failed with exit code 1
```

**Comment by squillace** [comment]
if you merge to master first, I should think you've already gotten the URL correctly calculated..... otherwise, this _must always run correctly and not fail_. Yes?

**Comment by MikeLarah** [comment]
Closing this issue as this specific case is fixed. I've created #41 to track the more general issue.
