### ISSUE TITLE
Thank you for sharing this excellent CNAB quickstarter for Mattermost! Interested in a guest blog post at mattermost.com/blog?

### ISSUE THREAD

**Issue by jasonblais** [Azure/azure-cnab-quickstarts#86]
@MikeLarah @JamesDawson @squillace This is an unconventional reachout, but with a good intention :) 

First and foremost, thank you for open sourcing this excellent CNAB quickstarter for Mattermost. I found about it through this tweet by you, Ralph Squillace: https://twitter.com/ralph_squillace/status/1296829626455658496

I'd love to promote your work with the Mattermost community. I'm curious if you were open to writing a guest blog post for mattermost.com/blog about the this package you built? Alternatively, I'd be happy to meet briefly and write a short article based on our conversation (with your reviews if preferred, of course).

This would make it easier for us to share your work with others who are looking for a quick package to get started on Azure.

Let me know if you're open to it?

**Comment by MikeLarah** [comment]
@jasonblais thanks for reaching out - happy to discuss this further. I've followed you on twitter so we can carry on the conversation over DM.
