### ISSUE TITLE
[porter/aks how to build azure once click UI

### ISSUE THREAD

**Issue by ccittadino-ctic** [Azure/azure-cnab-quickstarts#96]
Can someone please help me understand how the simple/advanced Azure one-click UIs are built? Is this something we have to build ourselves each time or does this project help build them based on the porter.yaml?

**Comment by HowardvanRooijen** [comment]
Do you mean the "Deploy from Azure" button?

**Comment by ccittadino-ctic** [comment]
Thanks @HowardvanRooijen ! Yep that is what I'm looking for. I assume then that there's nothing in this quickstart (or related tooling) that builds the json for you?

**Comment by HowardvanRooijen** [comment]
The JSON is just an ARM template!

**Comment by ccittadino-ctic** [comment]
Ok thanks @HowardvanRooijen I'll take that to mean "just use the template, there is no functionality to build it in this project".
